ST_CIC_WA_1_0 Release/feature branch
hmcts/am-org-role-mapping-service pull request #1472
Opened 2023-06-14 13:49 UTC by abul-syed

### JIRA link (if applicable) ###

- [AM-2714](https://tools.hmcts.net/jira/browse/AM-2714) - ST_CIC_WA - Add mapping rules in ORM for ST judges
   - [AM-2717](https://tools.hmcts.net/jira/browse/AM-2717) - ST_CIC_WA - Drool JUnit testing in ORM and RAS applications for JUDICIAL users
- [AM-2716](https://tools.hmcts.net/jira/browse/AM-2716) - ST_CIC_WA - Add mapping rules in ORM for STAFF users
   - [AM-2718](https://tools.hmcts.net/jira/browse/AM-2718) - ST_CIC_WA - Drool JUnit testing in ORM and RAS applications for STAFF users

### Change description ###

ST_CIC_WA_1_0 Release/feature branch:

- #1456 
- #1469 
- #1458

> NB: This PR is has a dependency on hmcts/am-role-assignment-service#

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-07-18 11:31 UTC, mattnayler requested changes

2023-07-18 11:31 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicStaffOrgRoleTest.java
> +            "2,BBA2,'tribunal-caseworker,hmcts-legal-operations,task-supervisor,case-allocator',Y,Y"
Can we have usual test with and without CaseAllocator and TaskSupervisor flags.

2023-07-18 11:31 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicStaffOrgRoleTest.java
> +            "10,BBA2,'ctsc,hmcts-ctsc,task-supervisor,case-allocator',Y,Y"
Can we have usual test with and without CaseAllocator and TaskSupervisor flags.

2023-07-20 15:19 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicStaffOrgRoleTest.java
> +    })
Resolved in 96a109309c7a0fba26d68b2193c97b29c0b25fb1

2023-07-20 15:28 UTC, mattnayler commented on src/main/resources/validationrules/stcic/stcic-judicial-office-holder-mapping.drl
> +   $jap: JudicialAccessProfile(appointment != null,
Resolved in 96a109309c7a0fba26d68b2193c97b29c0b25fb1

2023-07-20 15:46 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicStaffOrgRoleTest.java
> +            "2,BBA2,'tribunal-caseworker,hmcts-legal-operations,task-supervisor,case-allocator',Y,Y"
Resolved in #1514, see 94c4d04cf6b44c0b39ba31e417707bf90397cbe3.

2023-07-21 10:57 UTC, mattnayler commented on src/main/resources/validationrules/stcic/stcic-judicial-office-holder-mapping.drl
> + * 1: "ST_CIC President of Tribunal-Salaried" business role mapping to JOH.
See also f285545b0d39e0e972a45a8b79ab1d84f2b20400 and 8af3f10f4ed6dfee817d9beb45ba6d4a7914b7cd.

2023-07-21 11:12 UTC, mattnayler approved these changes
Approved at de2ec5fc17953f8eb3633858dc714ec0c8e5025a after merger of #1514.

2023-07-21 13:52 UTC, mikebrownccd approved these changes
LGTM

2023-07-26 12:55 UTC, abul-syed commented on src/main/resources/validationrules/stcic/stcic-judicial-org-role-mapping.drl
> +   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("hearing_work,decision_making_work,routine_work,"
`attribute.put("bookable", JacksonUtils.convertObjectIntoJsonNode("true"));`

`fee-paid-judge` missing bookable attribute. ExUI checks for this attribute to allow the user with role `fee-paid-judge` to create a booking.

2023-08-03 09:23 UTC, mattnayler reviewed
Re-reviewed after fc09f7bb671b4d0f50018ed4797b2c553d414011 subject to #1529.

2023-08-03 13:33 UTC, mattnayler approved these changes
Re-approved after merger of #1529, see d18c85a2b54d75c7e95f09661e503b04f578adc7.

2023-08-21 09:36 UTC, mattnayler approved these changes
Re-approved at 3e80f55f47973a1cb81b15cd385c465d5d00f028.

2023-08-21 14:24 UTC, mattnayler approved these changes
Re-reviewed at 9ebab30b72763ace7b52df75e94a9bb9825fe21d.

2023-08-21 14:56 UTC, mattnayler approved these changes
Re-approved after merger of #1546, see b98872c480179cacf1e8a89c955c2c8d0fe0bbe0.

2023-08-21 15:45 UTC, mikebrownccd approved these changes
LGTM

2023-08-29 14:51 UTC, merged