AM-2911:  Judicial Refresh (via ASB or Job) to include Judicial Bookings
hmcts/am-org-role-mapping-service pull request #1575
Opened 2023-09-13 16:09 UTC by prashanthkumarnb

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/AM-2911

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ *] No
```

2023-10-23 14:10 UTC, mattnayler requested changes

2023-10-24 15:36 UTC, prashanthkumarnb commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java
> +        if (null != responseEntity) {
[Null_pointers_shouldNot_Dereferenced.pdf](https://github.com/hmcts/am-org-role-mapping-service/files/13120283/Null_pointers_shouldNot_Dereferenced.pdf)

2023-10-24 15:38 UTC, prashanthkumarnb commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialBookingServiceTest.java
> +    void testFetchJudicialBookingsInBatchesWithUsers() {
addressed

2023-10-24 15:38 UTC, prashanthkumarnb commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java
> +            log.info("UserType not supported {}",userType);
addressed

2023-10-24 15:38 UTC, prashanthkumarnb commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java
> +        if (null != responseEntity) {
addressed

2023-10-24 15:38 UTC, prashanthkumarnb commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java
> +        doReturn(TestDataBuilder.buildUserAccessProfileMap(false, false)).when(retrieveDataService)
addressed

2023-10-24 15:39 UTC, prashanthkumarnb commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java
> +        Mockito.when(requestMappingService.createJudicialAssignments(Mockito.any(), Mockito.any()))
addressed

2023-10-24 15:39 UTC, prashanthkumarnb commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java
> +                .createJudicialAssignments(Mockito.any(),Mockito.any());
addressed

2023-10-24 15:39 UTC, prashanthkumarnb commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java
> +            List<String> uniqueUserIds = userIds.stream().distinct().toList();
the code looked complex with less readability , let me know when we pair we can discuss

2023-10-24 15:40 UTC, prashanthkumarnb commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java
> +        Mockito.when(requestMappingService.createJudicialAssignments(any(), any()))
addressed

2023-10-24 15:40 UTC, prashanthkumarnb commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialBookingService.java
> +        final int defaultBatchSize = Integer.parseInt(batchSize);
addressed

2023-10-24 16:08 UTC, mattnayler commented on Jenkinsfile_CNP
> +// TODO env.JUDICIAL_BOOKING_URL = "http://am-judicial-booking-service-aat.service.core-compute-aat.internal"
Resolved in 457da23aac8e8b48f48d4648caafb65985e72af0.

2023-10-24 16:23 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java
> +            log.info("UserType not supported {}",userType);
Resolved in 9d50d3f80627384371507e4fce692d5c5a687968.

2023-10-25 08:37 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialBookingServiceTest.java
> +    void testFetchJudicialBookingsInBatchesWithUsers() {
Resolved in 9d50d3f80627384371507e4fce692d5c5a687968.

2023-10-25 08:38 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java
> +        doReturn(TestDataBuilder.buildUserAccessProfileMap(false, false)).when(retrieveDataService)
Resolved in 9d50d3f80627384371507e4fce692d5c5a687968.

2023-10-25 08:44 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java
> +        Mockito.when(requestMappingService.createJudicialAssignments(Mockito.any(), Mockito.any()))
Resolved in 9d50d3f80627384371507e4fce692d5c5a687968.

2024-03-11 16:27 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java
> +        if (null != responseEntity) {
Also refactored in #1820.

2024-03-11 16:29 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java
> +    void createJudicialBulkAssignmentsRequestTest() {
Also refactored in #1820.

2024-03-13 15:35 UTC, mattnayler commented on src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java
> +        doReturn(buildJudicialBookingsResponse()).when(jbsFeignClient).getJudicialBookingByUserIds(any());
Refactored in #1820.

2024-03-13 15:36 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java
> +            List<String> uniqueUserIds = userIds.stream().distinct().toList();
Refactored in #1820.  Code moved to utility class to simplify edge case testing.

2024-03-13 15:37 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java
> +        Mockito.when(requestMappingService.createJudicialAssignments(any(), any()))
Refactored in #1820.  The code for conveting the nested map in to a list has been moved to utility class to simplify edge case testing.

2024-03-13 15:38 UTC, mattnayler commented on src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java
> +    private static final String  STAFF_URI = "/am/role-mapping/staff/users";
Refactored in #1820.

2024-03-15 17:28 UTC, mattnayler submitted a review, later dismissed
Re-reviewed after merger of #1820 (75bbff07bef5dc5583db5732fc93dffc3e880b7a) and master (5c2e3a048b6d22d174718c4f426d861b3cd89926).

2024-03-19 15:47 UTC, mikebrownccd submitted a review, later dismissed
LGTM

2024-04-29 14:16 UTC, mattnayler approved these changes
Re-approved after merger of: 
* #1826
* #1889
* #1869

2024-04-29 15:21 UTC, mikebrownccd approved these changes
LGTM

2024-05-09 10:34 UTC, merged