Ga 48 create table profile refresh queue
hmcts/am-org-role-mapping-service pull request #1711
Opened 2024-01-02 14:20 UTC by patelila

### Jira link (if applicable)

### Change description ###

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2024-01-03 13:34 UTC, sanjayparekh-hmcts requested changes

2024-01-03 13:34 UTC, sanjayparekh-hmcts commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/data/ProfileRefreshQueueTest.java
> +    private final ProfileRefreshQueueRepository profileRefreshQueueRepository
is this a test for the PRQ object or repository?
you seem to be mixing here?

2024-01-03 13:49 UTC, abul-syed commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/data/ProfileRefreshQueueTest.java
> +public class ProfileRefreshQueueTest {
```suggestion
class ProfileRefreshQueueTest {
```

code smell

2024-01-03 15:59 UTC, helenbirdhmcts requested changes

2024-01-04 11:24 UTC, helenbirdhmcts approved these changes
lgtm

2024-01-05 15:55 UTC, sanjayparekh-hmcts submitted a review, later dismissed

2024-01-08 10:02 UTC, abul-syed submitted a review, later dismissed

2024-01-08 10:02 UTC, helenbirdhmcts approved these changes

2024-01-17 12:21 UTC, abul-syed approved these changes

2024-01-18 09:17 UTC, sanjayparekh-hmcts approved these changes

2024-02-01 15:57 UTC, poojithanag approved these changes
QA Approved

2024-02-01 16:27 UTC, merged