GA PRM master
hmcts/am-org-role-mapping-service pull request #1737
Opened 2024-02-01 16:11 UTC by abul-syed

## PRM ##

### PRM internal data ###

[GA-47](https://tools.hmcts.net/jira/browse/GA-47) - PRM : Create table access_types
[GA-48](https://tools.hmcts.net/jira/browse/GA-48) - PRM : Create table profile_refresh_queue
[GA-49](https://tools.hmcts.net/jira/browse/GA-49) - PRM : Create table organisation_refresh_queue
[GA-50](https://tools.hmcts.net/jira/browse/GA-50) - PRM : Create table user_refresh_queue
[GA-99](https://tools.hmcts.net/jira/browse/GA-99) - PRM : Create table batch_last_run_timestamp
[GA-170](https://tools.hmcts.net/jira/browse/GA-170) - PRM : Update organisation_refresh_queue and user_refresh_queue queue to capture retry and retry_after
[GA-163](https://tools.hmcts.net/jira/browse/GA-163) - PRM : Update organisation_refresh_queue and user_refresh_queue queue to track user_last_updated

- #1710 
- #1711 
- #1713 
- #1719 
- #1720 
- #1772 
- #1786 

### PRM Processes ###

[GA-54](https://tools.hmcts.net/jira/browse/GA-54) - PRM : Process 1 - Find Case Definition Changes
[GA-55](https://tools.hmcts.net/jira/browse/GA-55) - PRM : Process 2 - Find Organisations with Stale Profiles
[GA-56](https://tools.hmcts.net/jira/browse/GA-56) - PRM : Process 3 - Find Organisation Changes
[GA-57](https://tools.hmcts.net/jira/browse/GA-57) - PRM : Process 4 - Find Users with Stale Organisations
[GA-58](https://tools.hmcts.net/jira/browse/GA-58) - PRM : Process 5 - Find User Changes
[GA-52](https://tools.hmcts.net/jira/browse/GA-52) - PRM : Process 6 - Refresh - Single User Mode and new PRM endpoint
[GA-53](https://tools.hmcts.net/jira/browse/GA-53) - PRM : Process 6 - Refresh Users - Batch Mode
- #1767
- #1743
- #1744  
- #1761 
- #1759 
- #1769
- #1802 

### PRM Process Monitoring & Alerts ###

[GA-184](https://tools.hmcts.net/jira/browse/GA-184) - PRM: Monitor Processes & Alerts
[GA-185](https://tools.hmcts.net/jira/browse/GA-185) - Add monitoring DTOs & re-usable tracking component
- #1798
- #1797 

### Dependencies ###

NB: The above processes have dependencies on external services. Some of the **direct** dependencies are:

P1: hmcts/ccd-definition-store-api#1438 - New CCD endpoint to retrieve Organisation Profile
P2: hmcts/rd-professional-api#1569 - New PRD endpoint to retrieve organisations by profile ids
P3: hmcts/rd-professional-api#1533 - Update to existing PRD GET /refdata/internal/v1/organisations/
P4: hmcts/rd-professional-api#1570 - New POST /refdata/internal/v2/organisations/users
P5: hmcts/rd-professional-api#1529 - New GET /refdata/internal/v1/users/ endpoint
P6: hmcts/am-role-assignment-service#2062 - New professional drool rule

2025-03-11 11:32 UTC, markharriscgi commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationService.java
> +            retrieveOrganisationsByProfileIdsAndUpsert(request, maxVersion.get());
Sonarqube wants maxVersion.get() to be prefixed by a maxVersion.isPresent().

2025-03-11 11:33 UTC, markharriscgi commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PrdService.java
> +                        new ArrayList<OrganisationInfo>(), false);
No need for the < OrganisationInfo>.  Can be replaced wiith <>

2026-01-19 13:51 UTC, markharriscgi approved these changes, later dismissed
LGTM

2026-04-23 11:44 UTC, mattnayler requested changes

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/resources/sql/insert_access_types.sql
> +-- VALUES (1, '{ "organisation_profiles": { "SOLICITOR_ORG": { "CIVIL": { "access_type_id": "at1", "access_mandatory": false, "access_default": false, "roles": [], "case_type_id": "ctId", "organisati
Can this be cleaned up.

2026-04-23 11:44 UTC, mattnayler commented on src/test/resources/userAccessType.json
> +  {
Is this needed here given I can only find a reference in `src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtilsTest.java`?

2026-04-23 11:44 UTC, mattnayler commented on src/main/resources/prdRefreshUserSample138.json
> +  "users": [
Is this still needed here given I cannot find a reference in code?

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/cleanup/insert_new_organisation_refresh_queue.sql
> +INSERT INTO organisation_refresh_queue (organisation_id, last_updated, organisation_last_updated, access_types_min_version, active)
Is this the correct name for this script?

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/cleanup/insert_old_active_organisation_refresh_queue.sql
> +INSERT INTO organisation_refresh_queue (organisation_id, organisation_last_updated, last_updated, access_types_min_version, active)
Is this the correct name for this script?

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/cleanup/insert_new_active_organisation_refresh_queue.sql
> +INSERT INTO organisation_refresh_queue (organisation_id, organisation_last_updated, last_updated, access_types_min_version, active)
Is this the correct name for this script?

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/cleanup/insert_old_organisation_refresh_queue.sql
> +INSERT INTO organisation_refresh_queue (organisation_id, organisation_last_updated, last_updated, access_types_min_version, active)
Is this the correct name for this script?

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/profile_refresh_queue/insert_Solicitor_Profile.sql
> +INSERT INTO profile_refresh_queue (organisation_profile_id, access_types_min_version, active)
Is this a duplicate?

2026-04-23 11:44 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/apihelper/Constants.java
> +    public static final String SINCE_TIMESTAMP_FORMAT = "yyyy-MM-dd'T'HH:mm:ss";
Is this adupiccate of: src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/constants/PrmConstants.java

2026-04-23 11:44 UTC, mattnayler commented on src/main/resources/samples/prd/usersByOrganisationSample.json
> +          "email": "bulkuser.admin@hmcts.net",
Can we reset example data to something more test like.

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/scheduler/PrmSchedulerProcess3IntegrationTest.java
> +        // verify that the OrganisationRefreshQueue contains 3 records
Assumed typo

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/resources/SchedulerTests/role_assignments/senior_tribunal_caseworker.json
> +{
I think this test file is obsolete (or atleast not relevant for PRM)

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/resources/SchedulerTests/PrdRetrieveUsers/user_template.json
> +{
This file may not be required

2026-04-23 11:44 UTC, mattnayler commented on src/integrationTest/resources/sql/insert_populated_access_types.sql
> +DELETE FROM access_types;
This file may not be required

2026-04-23 11:44 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/testingsupport/PrmSchedulerControllerTest.java
> +class PrmSchedulerControllerTest {
Needs tests for Process6 and two clean up processes.

2026-04-23 11:53 UTC, mattnayler commented on src/integrationTest/resources/SchedulerTests/PrdRetrieveUsers/user_template.json
> +{
This file is required: see `src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/scheduler/BaseProcess6IntegrationTest.java`.

2026-04-23 12:52 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/profile_refresh_queue/insert_Solicitor_Profile.sql
> +INSERT INTO profile_refresh_queue (organisation_profile_id, access_types_min_version, active)
To be resolved in: 0d3ad5b1097271711937725db31d862b58c83edd, see #2731.

2026-04-23 12:52 UTC, mattnayler commented on src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/scheduler/PrmSchedulerProcess3IntegrationTest.java
> +        // verify that the OrganisationRefreshQueue contains 3 records
To be resolved in: 9297dfee404a4095acf5b0b874fe3169755a4265, see #2731.

2026-04-23 12:53 UTC, mattnayler commented on src/integrationTest/resources/SchedulerTests/role_assignments/senior_tribunal_caseworker.json
> +{
To be resolved in: 9297dfee404a4095acf5b0b874fe3169755a4265, see #2731.

2026-04-23 12:53 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/cleanup/insert_new_active_organisation_refresh_queue.sql
> +INSERT INTO organisation_refresh_queue (organisation_id, organisation_last_updated, last_updated, access_types_min_version, active)
To be resolved in: 9297dfee404a4095acf5b0b874fe3169755a4265, see #2731.

2026-04-23 12:53 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/cleanup/insert_new_organisation_refresh_queue.sql
> +INSERT INTO organisation_refresh_queue (organisation_id, last_updated, organisation_last_updated, access_types_min_version, active)
To be resolved in: 9297dfee404a4095acf5b0b874fe3169755a4265, see #2731.

2026-04-23 12:53 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/cleanup/insert_old_active_organisation_refresh_queue.sql
> +INSERT INTO organisation_refresh_queue (organisation_id, organisation_last_updated, last_updated, access_types_min_version, active)
To be resolved in: 9297dfee404a4095acf5b0b874fe3169755a4265, see #2731.

2026-04-23 12:53 UTC, mattnayler commented on src/integrationTest/resources/sql/prm/cleanup/insert_old_organisation_refresh_queue.sql
> +INSERT INTO organisation_refresh_queue (organisation_id, organisation_last_updated, last_updated, access_types_min_version, active)
To be resolved in: 9297dfee404a4095acf5b0b874fe3169755a4265, see #2731.

2026-04-23 12:53 UTC, mattnayler commented on src/integrationTest/resources/sql/insert_access_types.sql
> +-- VALUES (1, '{ "organisation_profiles": { "SOLICITOR_ORG": { "CIVIL": { "access_type_id": "at1", "access_mandatory": false, "access_default": false, "roles": [], "case_type_id": "ctId", "organisati
To be resolved in: 9297dfee404a4095acf5b0b874fe3169755a4265, see #2731.

2026-04-23 13:13 UTC, mattnayler commented on src/integrationTest/resources/sql/insert_populated_access_types.sql
> +DELETE FROM access_types;
To be resolved in: 68967302de1a92ef73d96c9a1845864c4e27c3aa, see #2731.

2026-04-23 13:45 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/apihelper/Constants.java
> +    public static final String SINCE_TIMESTAMP_FORMAT = "yyyy-MM-dd'T'HH:mm:ss";
To be resolved in: be9e0433c3945d0e5ae424fdc46f69042f6df3a9, see #2731.

2026-04-23 13:49 UTC, mattnayler commented on src/test/resources/userAccessType.json
> +  {
To be resolved in: 0e991a7fd241541e410e3aaccdbd36d73bf0755e, see #2731.

2026-04-23 13:49 UTC, mattnayler commented on src/main/resources/prdRefreshUserSample138.json
> +  "users": [
To be resolved in: 0e991a7fd241541e410e3aaccdbd36d73bf0755e, see #2731.

2026-04-23 13:52 UTC, mattnayler commented on src/main/resources/samples/prd/usersByOrganisationSample.json
> +          "email": "bulkuser.admin@hmcts.net",
To be resolved in: be9e0433c3945d0e5ae424fdc46f69042f6df3a9, see #2731.

2026-04-23 15:00 UTC, mattnayler reviewed
Approved for release into Demo & PerfTest for BAT

2026-04-27 16:52 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/testingsupport/PrmSchedulerControllerTest.java
> +class PrmSchedulerControllerTest {
This will be resolved in 88061cc6998dbd179b4855f5241a2f9e46e302ae, see #2736.

2026-05-27 14:02 UTC, mattnayler commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/testingsupport/PrmSchedulerControllerTest.java
> +class PrmSchedulerControllerTest {
Resolved in b7e979e6a7ea5562338e2c7d8bc4e01f80ff56d1.

2026-05-27 14:15 UTC, markharriscgi approved these changes
LGTM

2026-05-27 14:29 UTC, mattnayler approved these changes

2026-05-27 15:00 UTC, merged