Ga 58 p5 find user changes
hmcts/am-org-role-mapping-service pull request #1759
Opened 2024-02-14 16:31 UTC by sanjayparekh-hmcts

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/GA-58

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-03-05 16:40 UTC, shaed-parkar commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationService.java
> +            int page = 2;
a do/while loop might be better suited here if you know you have to call the api at least once?

2024-03-05 16:42 UTC, shaed-parkar commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationService.java
> +            processMonitorDto.markAsFailed(exception.getMessage());
I think this is a good instance of tracking successful and unsuccessful jobs and marks as partially failed

2024-03-06 13:54 UTC, shaed-parkar approved these changes
Looks good!

2024-03-08 12:25 UTC, TomForniCGI approved these changes
LGTM

2025-06-20 16:12 UTC, mattnayler requested changes
AM Review comments to be addressed in [DTSAM-931](https://tools.hmcts.net/jira/browse/DTSAM-931).

2025-06-24 10:33 UTC, mattnayler reviewed
Re reviewed after merge conflict (7ac25fe198649f11514550b88dc6798b6135b482).  See previous AM Review comments to be addressed in [DTSAM-931](https://tools.hmcts.net/jira/browse/DTSAM-931).

2025-06-26 11:49 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/ProfessionalUserBuilder.java
> +    public static RefreshUserAndOrganisation getSerializedRefreshUser(RefreshUser user) {
Will be resolved by 4e0811853acc077824ef5ad48cf250173c7ce054 and efa49edbe86ae0524fa628a76a62382deec7982e in #2351

2025-06-26 11:49 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/UserRefreshQueueRepository.java
> +                        + ":accessTypes, :organisationId, :organisationStatus, "
Will be resolved by 3493cf24d0977862bbcd0af47846fbfd9321b0dd in #2351

2025-06-26 12:13 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PrdService.java
> +        return prdFeignClient.retrieveUsers(lastUpdatedSince, pageSize, searchAfter);
Tests in AAT for `GET /refdata/internal/v1/organisations/users`. When no results returned response was 200 and an empty users list.

So no action required.

2025-06-30 09:48 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ProfessionalUserService.java
> +                while (moreAvailable) {
Will be resolved by d85c80288e8924c197479bc99a6339358067eb98 in #2351

2025-06-30 09:48 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ProfessionalUserService.java
> +    private void appendLastProcessStep(ProcessMonitorDto processMonitorDto, String message) {
Will be resolved by 08aa59251c4ae1cd4f8144dc4d52a5228e16927c in #2351

2025-07-10 16:15 UTC, merged