DTSAM-491 Decommission Launch Darkly ORM
hmcts/am-org-role-mapping-service pull request #2081
Opened 2024-09-04 11:29 UTC by mikebrownccd

### Jira link
https://tools.hmcts.net/jira/browse/DTSAM-491

### Change description
Decommission Launch Darkly ORM

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] Does this PR introduce a breaking change

2025-02-03 12:24 UTC, mattnayler requested changes

2025-02-03 12:24 UTC, mattnayler commented on src/functionalTest/resources/features/F-000/F-000.feature
> +  @FeatureToggle(DB:iac_1_1=on)
test can be removed as now it is a duplicate of `@S-111`

2025-02-03 12:24 UTC, mattnayler commented on src/functionalTest/resources/features/F-004/F-004.feature
> -  @FeatureToggle(LD:orm-judicial-refresh-role-api=on) @FeatureToggle(LD:jbs-create-bookings-api-flag=on)
Can we have a JBS EV to turn these off if JBS is broken in AAT.

2025-02-04 15:20 UTC, mattnayler commented on src/functionalTest/resources/features/F-000/F-000.feature
> +  @FeatureToggle(DB:iac_1_1=on)
Resolved in 437c0fc162f7ba823d16d9689e9f343dbeb16b5b.

2025-02-04 15:22 UTC, mattnayler commented on src/functionalTest/resources/features/F-004/F-004.feature
> -  @FeatureToggle(LD:orm-judicial-refresh-role-api=on) @FeatureToggle(LD:jbs-create-bookings-api-flag=on)
Resolved in 437c0fc162f7ba823d16d9689e9f343dbeb16b5b.

2025-02-10 11:42 UTC, lukasz-wolski commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/JobConfiguration.java
> +                            @Value("${refresh.Job.updateOverride}") Boolean  jobDetailAllowUpdate
minor: extra space between Boolean and jobDetailAllowUpdate

2025-02-10 12:00 UTC, lukasz-wolski submitted a review, later dismissed
LGTM

2025-02-10 13:26 UTC, prashanthnerligeb submitted a review, later dismissed
LGTM

2025-02-10 16:55 UTC, mattnayler commented on src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/JobConfiguration.java
> +                            @Value("${refresh.Job.updateOverride}") Boolean  jobDetailAllowUpdate
Updated in 8e9ee4fc4b96d03f3029cb099baf2f7c68fb46eb.

2025-02-10 17:08 UTC, lukasz-wolski approved these changes

2025-02-11 15:01 UTC, prashanthnerligeb approved these changes
LGTM

2025-02-11 15:22 UTC, mattnayler approved these changes
Approved after changes by me approved by two others

2025-02-13 11:52 UTC, merged