COT-917: Add removed judge and bookable for identified fee-paid judge
hmcts/am-org-role-mapping-service pull request #2155
Opened 2024-11-05 13:58 UTC by ben-james-hmcts

Revert "COT-912 ST_CIC remove booked judge role assignment"
Reverts hmcts/am-org-role-mapping-service#2145

2024-11-05 17:00 UTC, abul-syed requested changes
nice PR, minor feedback

2024-11-05 17:00 UTC, abul-syed commented on src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialRoleMappingTest.java
> +    static void assertCommonRoleAssignmentAttributes(RoleAssignment r, String office, List<String> ticketCodes) {
should we can omit `office` & `ticketCodes` from input param as not used in test?

2024-11-05 17:38 UTC, abul-syed approved these changes
lgtm

2024-11-06 09:12 UTC, mattnayler approved these changes
LGTM

2024-11-08 10:44 UTC, merged